//
// Created by James on 8/24/2022.
//

#ifndef COMPUTEBOIDS_VULKAN_INCLUDES_HPP
#define COMPUTEBOIDS_VULKAN_INCLUDES_HPP

#endif //COMPUTEBOIDS_VULKAN_INCLUDES_HPP

#pragma once

#define VULKAN_HPP_DISPATCH_LOADER_DYNAMIC 1
#define VULKAN_HPP_TYPESAFE_CONVERSION 1
#define VULKAN_HPP_NO_CONSTRUCTORS
#define VULKAN_HPP_NO_EXCEPTIONS

#include <vulkan/vulkan.hpp>